---
- name: Configure Environment
  hosts: localhost
  become: yes
  tasks:
    # Update and upgrade the system
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    # Install zsh
    - name: Install Zsh
      apt:
        name: zsh
        state: present
        update_cache: yes

    - name: Change default shell to Zsh
      shell: chsh -s $(which zsh) "{{ ansible_user }}"
      args:
        executable: /bin/bash  # Ensure the shell used for the command is compatible
      changed_when: false  # Avoid false positives since `chsh` may not change the shell if it's already set

    - name: Install Oh My Zsh
      shell: |
        curl -Lo install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        bash install.sh --unattended
      args:
        creates: ~/.oh-my-zsh  # Skip if already installed
      environment:
        ZSH: "~/.oh-my-zsh"

    - name: Install Zsh plugin for auto-complete
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
        update: yes

    - name: Update .zshrc to include autosuggestions
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins='
        line: "plugins=(git zsh-autosuggestions)"
        backrefs: yes

    # Install Nerd Fonts
    - name: Download and install Nerd Fonts
      shell: |
        mkdir -p ~/.local/share/fonts
        cd ~/.local/share/fonts
        curl -fLo "FiraCode Nerd Font.ttf" https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        unzip FiraCode.zip
        fc-cache -fv

    # Install Neovim
    - name: Install Neovim
      apt:
        name: neovim
        state: present

      # Install Rust
    - name: Install Rust programming language
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      environment:
        CARGO_HOME: ~/.cargo
        RUSTUP_HOME: ~/.rustup

    # Install C and C++ compilers
    - name: Install C and C++ compilers
      apt:
        name:
          - build-essential
          - gcc
          - g++
        state: present

    # Install Go
    - name: Install Go programming language
      apt:
        name: golang-go
        state: present

    # Install Zig
    - name: Install Zig programming language
      shell: |
        wget https://ziglang.org/download/index.html -O zig.tar.xz
        mkdir -p ~/.local/bin
        tar -xf zig.tar.xz --directory ~/.local/bin --strip-components=1
      args:
        creates: ~/.local/bin/zig

    # Install Docker
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Print post-installation note
      debug:
        msg: |
          Device is now setup
