- name: Setup System for Zsh and Essential Configuration
  hosts: localhost
  become: yes
  tasks:
    # Ensure the system is updated
    - name: Update apt cache and upgrade the system
      apt:
        update_cache: yes
    # Install zsh
    - name: Install Zsh
      apt:
        name: zsh
        state: present
        update_cache: yes
    - name: Change default shell to Zsh
      shell: chsh -s $(which zsh)
      args:
        executable: /bin/bash  # Ensure the shell used for the command is compatible
      changed_when: false  # Avoid false positives since `chsh` may not change the shell if it's already set
    - name: Install Oh My Zsh
      shell: |
        curl -Lo install.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        bash install.sh --unattended
      args:
        creates: ~/.oh-my-zsh  # Skip if already installed
      environment:
        ZSH: "~/.oh-my-zsh"
    - name: Install Zsh plugin for auto-complete
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
        update: yes
    - name: Update .zshrc to include autosuggestions
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins='
        line: "plugins=(git zsh-autosuggestions)"
        backrefs: yes
    # Install Nerd Fonts
    - name: Download and install Nerd Fonts
      shell: |
        mkdir -p ~/.local/share/fonts
        cd ~/.local/share/fonts
        curl -fLo "FiraCode Nerd Font.ttf" https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
        unzip FiraCode.zip
        fc-cache -fv
      args:
        creates: "~/.local/share/fonts/FiraCode Nerd Font.ttf"  # Skip if already downloaded
