name: Test Ansible Playbooks

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test-ansible-yamls:
    name: Test YAML Configurations
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python for Ansible
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Ansible and linting tools
      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

     # Step 4: Validate YAML syntax for all task files
      #- name: Validate YAML syntax
       # run: |
      #    for file in ./tasks/*.yml; do
       #     echo "Validating $file..."
      #      ansible-playbook --syntax-check $file || exit 1
      #    done

      # Step 5: Lint task files
      #- name: Lint Ansible task files
      #  run: |
       #   for file in ./tasks/*.yml; do
       #     echo "Linting $file..."
        #    ansible-lint -v $file
        #  done

       # Step 6: Test task files (Dry Run) with `zsh-setup.yml` first
      - name: Test task files in a playbook context
        run: |
          # Test the playbook
          ansible-playbook playbook.yml --check
